name: CI-CD

on:
  push:
    branches: [ "main", "master", "feature/**" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - name: Build + Test + Coverage + Static Analysis
        run: mvn -B clean verify

  build-image:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devops-exercise:${{ github.sha }}

  deploy:
    needs: build-image
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: self-hosted   # tu runner local con Podman
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Podman
        env:
          IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/devops-exercise:${{ github.sha }}
          JWT_SECRET_B64: ${{ secrets.JWT_SECRET_B64 }}
        run: |
          echo "JWT_SECRET_B64=$JWT_SECRET_B64" > .env
          podman pull $IMAGE_TAG
          podman compose down || true
          podman compose up -d --build
