name: devops

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      - name: Build + Test
        run: mvn -B clean verify

  build-image:
    needs: build-test
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devops-exercise
    outputs:
      image_tag: ${{ steps.meta.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEVOPS_PWD }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:main
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
      - name: Set IMAGE_TAG output
        id: meta
        run: echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
  deploy:
    needs: build-image
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: [self-hosted, Windows, X64]
    env:
      IMAGE_TAG: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Escribir .env para compose
        shell: powershell
        run: |
          "JWT_SECRET_B64=${{ secrets.JWT_SECRET_B64 }}" | Out-File -Encoding ASCII .env
          "IMAGE_TAG=${{ env.IMAGE_TAG }}" | Out-File -Encoding ASCII -Append .env
          Get-Content .env

      - name: Instalar podman-compose en carpeta temporal y usarlo
        shell: powershell
        run: |
          $python = "C:\Python311\python.exe"
          $podman = "C:\Program Files\RedHat\Podman\podman.exe"
          $moddir = "$env:RUNNER_TEMP\pdc"

          & $python -m pip install --upgrade pip
          if ($LASTEXITCODE -ne 0) { throw "pip upgrade failed" }

          & $python -m pip install podman-compose -t $moddir
          if ($LASTEXITCODE -ne 0) { throw "pip install podman-compose failed" }

          $env:PYTHONPATH = $moddir

          # (Opcional) ver versión
          & $python -m podman_compose --version

          # Pull explícito de la imagen versionada de GHCR
          & $podman pull $env:IMAGE_TAG
          if ($LASTEXITCODE -ne 0) { throw "podman pull failed" }

          # DOWN (ignora error si no hay stack)
          & $python -m podman_compose down
          if ($LASTEXITCODE -ne 0) { Write-Host "no stack to stop"; $LASTEXITCODE = 0 }

          # UP con .env (usa IMAGE_TAG y JWT_SECRET_B64)
          & $python -m podman_compose up -d
          if ($LASTEXITCODE -ne 0) { throw "compose up failed" }

          # Ver contenedores
          & $podman ps
      - name: Smoke test /DevOp
        shell: pwsh
        run: |
          $line = (Get-Content .env | Select-String '^JWT_SECRET_B64=')
          if (-not $line) { throw "Falta JWT_SECRET_B64 en .env" }
          $env:JWT_SECRET_B64 = ($line.ToString().Split('=')[1]).Trim()
          if (-not $env:JWT_SECRET_B64) { throw "JWT_SECRET_B64 vacio" }

          $mvnw = "$PWD\mvnw.cmd"
          if (-not (Test-Path $mvnw)) { throw "mvnw.cmd no encontrado en $PWD" }

          $JWT = & $mvnw -q -Dexec.mainClass=com.diegog.devopsExercise.MintJwtRunner exec:java
          # Asegurar string plano sin CR/LF ni espacios
          $JWT = ($JWT -join '') -replace "`r|`n","" 
          if ([string]::IsNullOrWhiteSpace($JWT) -or $JWT.Split('.').Count -ne 3 -or $JWT.Length -lt 100) {
            throw "JWT invalido o vacio: '$JWT'"
          }
          Write-Host "JWT length: $($JWT.Length)"

          $Body = '{"message":"This is a test","to":"Juan Perez","from":"Rita Asturia","timeToLifeSec":45}'
          $code = & curl.exe -s -o resp.json -w "%{http_code}" -X POST `
            -H "X-Parse-REST-API-Key: 2f5ae96c-b558-4c7b-a590-a501ae1c3f6c" `
            -H "X-JWT-KWY: $JWT" `
            -H "Content-Type: application/json" `
            --data-raw $Body http://localhost:8080/DevOps

          Get-Content resp.json
          if ($code -ne "200") { throw "Smoke test FAILED. HTTP $code" }
