name: CI-CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}   

jobs:
  build-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '21'
        - name: Cache Maven
          uses: actions/cache@v4
          with:
            path: ~/.m2/repository
            key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        - name: Build + Test 
          run: mvn -B clean verify

  build-image:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devops-exercise
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEVOPS_PWD }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:main
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
      - name: Set IMAGE_TAG output
        id: meta
        run: echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-image        # o build-test si no haces imagen
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Escribir .env con secreto y tag
        shell: powershell
        run: |
          "JWT_SECRET_B64=${{ secrets.JWT_SECRET_B64 }}" | Out-File -Encoding ASCII .env
          "IMAGE_TAG=${{ needs.build-image.outputs.meta.IMAGE_TAG }}" | Out-File -Encoding ASCII -Append .env
          Get-Content .env

      - name: Compose con podman
        shell: powershell
        run: |
          $podman = "C:\Program Files\RedHat\Podman\podman.exe"
          & $podman login ghcr.io --username $env:${{ github.actor }} --password $env:${{ secrets.DEVOPS_PWD }}
          & $podman pull $env:IMAGE_TAG
          & $podman-compose down
          if ($LASTEXITCODE -ne 0) { Write-Host "no stack to stop"; $LASTEXITCODE = 0 }
          & $podman-compose up -d
